# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Excel2Map
                                 A QGIS plugin
 Esta herramienta crea un Mapa basado en datos de un archivo Excel
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-14
        copyright            : (C) 2025 by INEGI
        email                : soporte@inegi.org.mx
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Excel2Map class from file Excel2Map.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .excel2map import Excel2Map
    return Excel2Map(iface)
